services:
#  app:
#    image: spr-app:latest
#    restart: "no"
#    environment:
#      - DATABASE_PORT=5432
#      - DATABASE_HOST=postgres
#      - DATABASE_USERNAME=postgres
#      - DATABASE_PASSWORD=postgres
#      - DATABASE_NAME=postgres
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

  db:
    image: postgres:17.0-alpine3.20
    restart: no
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

volumes:
  pg_data: {}